# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YggLazyCli < Formula
  desc "Lazy-way Yggdrasil CLI Network configurator"
  homepage "https://github.com/Y-Akamirsky/ygg-lazy-cli"
  version "0.1.6-b"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-b/ygg-lazy-cli_0.1.6-b_darwin_amd64.tar.gz"
      sha256 "d3eb45b760a33727c39dbdb019acc06d15f71b952bfe664560b0b604a7b1e78c"

      def install
        bin.install "ygg-lazy-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-b/ygg-lazy-cli_0.1.6-b_darwin_arm64.tar.gz"
      sha256 "38699b788cb02a4eb2b3044df366f1daa8edd2ef3e6daaf65a244e27c0322662"

      def install
        bin.install "ygg-lazy-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-b/ygg-lazy-cli_0.1.6-b_linux_amd64.tar.gz"
      sha256 "9df7fffafcd6cda850c3b8675806c4ab15bd5bd7ae122ccfbf8ebcf99c41a26e"
      def install
        bin.install "ygg-lazy-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-b/ygg-lazy-cli_0.1.6-b_linux_arm64.tar.gz"
      sha256 "3795debddada7f3f123a07ba1d98a23b1bfbd7533f4e2a667304b9d77f4a86a0"
      def install
        bin.install "ygg-lazy-cli"
      end
    end
  end

  test do
    system "#{bin}/ygg-lazy-cli -h"
  end
end
