# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygglazy < Formula
  desc "Lazy-way CLI Yggdrasil Network configurator"
  homepage "https://github.com/Y-Akamirsky/ygg-lazy-cli"
  version "0.1.6-c"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_darwin_amd64.tar.gz.tar.gz"
      sha256 "3fa0ff3872ae63ae82c72a96e2eb4d240226e7040a16aec9e4d3c3b98f202270"

      def install
        bin.install "ygglazy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_darwin_arm64.tar.gz.tar.gz"
      sha256 "5964e97d2ed2c37f064653a4c01873d23c9781149f36946fe204831cd3539f96"

      def install
        bin.install "ygglazy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_linux_amd64.tar.gz.tar.gz"
      sha256 "be17fed223c589f21c7b3d0cbeb81f678d6d002a16e1f6a32a15286ad8aff7eb"
      def install
        bin.install "ygglazy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_linux_arm64.tar.gz.tar.gz"
      sha256 "3d46b9867f4ccad368ee57d5d78719f12350853feb5eb17ad4a6381d4206e740"
      def install
        bin.install "ygglazy"
      end
    end
  end

  test do
    system "#{bin}/ygglazy -h"
  end
end
