# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygglazy < Formula
  desc "Lazy-way CLI Yggdrasil Network configurator"
  homepage "https://github.com/Y-Akamirsky/ygg-lazy-cli"
  version "0.1.6-c"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_darwin_amd64.tar.gz"
      sha256 "26c731f64cf6f0687686a4e0621073d97101eb4fe48196dcefb9025428ee7f67"

      def install
        bin.install "ygglazy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_darwin_arm64.tar.gz"
      sha256 "204211e5ea36823210fc2b1c9e630560613f859c3c6a934df843806cba82b1a9"

      def install
        bin.install "ygglazy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_linux_amd64.tar.gz"
      sha256 "739d072cf2f66ca70fd4091993a072d1fd33a5720e16084c28613aab571bfbdd"
      def install
        bin.install "ygglazy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Y-Akamirsky/ygg-lazy-cli/releases/download/0.1.6-c/ygglazy_0.1.6-c_linux_arm64.tar.gz"
      sha256 "34f558e83006d2d83168bacf9ffdf05debbc8b59c19554b4879c58327e89411a"
      def install
        bin.install "ygglazy"
      end
    end
  end

  test do
    system "#{bin}/ygglazy -h"
  end
end
